--1
CREATE TABLE FIGURY(
ID number(1) PRIMARY KEY,
KSZTALT MDSYS.SDO_GEOMETRY
);

DELETE FROM FIGURY;


--2
INSERT INTO FIGURY VALUES(
1,
SDO_GEOMETRY(
    2003,2002,
    NUL
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,4), -- one circle
    SDO_ORDINATE_ARRAY(3,5, 5,7, 7,5)
  )
);

INSERT INTO FIGURY VALUES(
2,
SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,3),
    SDO_ORDINATE_ARRAY(1,1, 5,5)

  )
);

INSERT INTO FIGURY VALUES(
3,
SDO_GEOMETRY(
    2002,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,4,2, 1,2,1, 5,2,2),
    SDO_ORDINATE_ARRAY(3,2, 6,2, 7,3, 8,2, 7,1)

  )
);

--3
INSERT INTO FIGURY VALUES(
4,
SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,4,2, 1,2,1, 5,2,2),
    SDO_ORDINATE_ARRAY(3,2, 6,2, 7,3, 8,2, 7,1)

  )
);

--4
SELECT ID, SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(KSZTALT,0.01) FROM FIGURY;

--5
DELETE FROM FIGURY WHERE
ID IN(
SELECT a.ID
FROM FIGURY a
WHERE SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(a.KSZTALT,0.01) NOT LIKE 'TRUE');

--6
COMMIT;